### ISSUE TITLE
Plugin does not work with CLI distribution due to CL problem

### ISSUE THREAD

**Issue by DirkMahler** [jqassistant-contrib/jqassistant-asciidoc-report-plugin#1]
Asciidoctor/JRuby cannot load the IncludeProcessor as the wrong classloader is used, should be the PluginClassloader.

**Comment by AndreasAumayr** [comment]
Hi
I think I just ran into this problem (see console output below).
Any chance to get this fixed in near future, or any further hint where to fix this? I am still new to JQA and just want to do some basic analysis using the CLI (providing a custom lib-directory and an asciidoc file containing the rules)..

Best regards,
Andreas

> 2019-03-04 15:51:43.726 [main] INFO PluginConfigurationReaderImpl - Loaded jQAssistant plugins [Asciidoc Report, CDI, Common, Core Analysis, Core Report, EJB3, GraphML, JAX-RS, JPA 2, JSON, JUnit, Jav
a, Java 8, Java EE 6, Maven 2 Repository, Maven 3, OSGi, RDBMS, Spring, TestNG, Tycho, XML, YAML].
2019-03-04 15:51:44.167 [main] INFO StoreFactory - Connecting to store at 'file:/D:/internaltools/JQAssistant/trunk/jqassistant/store/'
2019-03-04 15:51:50.139 [main] INFO EmbeddedGraphStore - Initializing embedded Neo4j server 3.x
2019-03-04 15:51:50.157 [main] INFO AbstractAnalyzeTask - Will warn on violations starting form severity 'MINOR'
2019-03-04 15:51:50.157 [main] INFO AbstractAnalyzeTask - Will fail on violations starting from severity 'MAJOR'.
2019-03-04 15:51:50.157 [main] INFO AbstractAnalyzeTask - Executing analysis.
2019-03-04 15:51:50.166 [main] INFO AbstractAnalyzeTask - Reading rules from directory D:\internaltools\JQAssistant\trunk\rules
2019-03-04 15:51:53.278 [main] INFO AbstractAnalyzeTask - Executing group 'xyz-rules:All'
2019-03-04 15:51:53.319 [main] INFO AbstractAnalyzeTask - Validating constraint 'xyz-rules:DummyConstraint' with severity: 'MINOR (from BLOCKER)'.
2019-03-04 15:51:54.049 [main] INFO AsciidocReportPlugin - Found index document 'D:\internaltools\JQAssistant\trunk\rules\index.adoc'.
2019-03-04 15:51:54.050 [main] INFO AsciidocReportPlugin - Calling for the Asciidoctor...
2019-03-04 15:51:54.760 [main] INFO AsciidocReportPlugin - Writing to report directory D:\internaltools\JQAssistant\trunk\jqassistant\report\asciidoc
2019-03-04 15:51:54.760 [main] INFO AsciidocReportPlugin - -> D:\internaltools\JQAssistant\trunk\rules\index.adoc
Exception in thread "main" org.jruby.exceptions.RaiseException: (NameError) cannot load Java class org.jqassistant.contrib.plugin.asciidocreport.IncludeProcessor
        at org.jruby.javasupport.JavaClass.for_name(org/jruby/javasupport/JavaClass.java:286)
        at org.jruby.javasupport.JavaUtilities.get_proxy_class(org/jruby/javasupport/JavaUtilities.java:34)
        at RUBY.block in java_import(uri:classloader:/jruby/java/core_ext/object.rb:49)
        at org.jruby.RubyArray.map(org/jruby/RubyArray.java:2487)
        at RUBY.java_import(uri:classloader:/jruby/java/core_ext/object.rb:36)
        at RUBY.<main>(<script>:1)
Caused by: java.lang.ClassNotFoundException: org.jqassistant.contrib.plugin.asciidocreport.IncludeProcessor
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.jruby.javasupport.JavaSupportImpl.loadJavaClass(JavaSupportImpl.java:154)
        at org.jruby.javasupport.JavaSupportImpl.loadJavaClassVerbose(JavaSupportImpl.java:163)
        at org.jruby.javasupport.JavaClass.forNameVerbose(JavaClass.java:271)
        at org.jruby.javasupport.JavaClass.for_name(JavaClass.java:286)
        at org.jruby.javasupport.Java.get_proxy_class(Java.java:386)
        at org.jruby.javasupport.JavaUtilities.get_proxy_class(JavaUtilities.java:34)
        at org.jruby.javasupport.JavaUtilities$INVOKER$s$1$0$get_proxy_class.call(JavaUtilities$INVOKER$s$1$0$get_proxy_class.gen)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_BLOCK(Interpreter.java:127)
        at org.jruby.runtime.InterpretedIRBlockBody.commonYieldPath(InterpretedIRBlockBody.java:141)
        at org.jruby.runtime.IRBlockBody.doYield(IRBlockBody.java:186)
        at org.jruby.runtime.BlockBody.yield(BlockBody.java:116)
        at org.jruby.runtime.Block.yield(Block.java:165)
        at org.jruby.RubyArray.collect(RubyArray.java:2473)
        at org.jruby.RubyArray.map19(RubyArray.java:2487)
        at org.jruby.RubyArray$INVOKER$i$0$0$map19.call(RubyArray$INVOKER$i$0$0$map19.gen)
        at org.jruby.internal.runtime.methods.JavaMethod$JavaMethodZeroBlock.call(JavaMethod.java:536)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:278)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:79)
        at org.jruby.runtime.callsite.CachingCallSite.callIter(CachingCallSite.java:84)
        at org.jruby.ir.instructions.CallBase.interpret(CallBase.java:429)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:360)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.InterpreterEngine.interpret(InterpreterEngine.java:84)
        at org.jruby.internal.runtime.methods.InterpretedIRMethod.INTERPRET_METHOD(InterpretedIRMethod.java:186)
        at org.jruby.internal.runtime.methods.InterpretedIRMethod.call(InterpretedIRMethod.java:173)
        at org.jruby.runtime.callsite.CachingCallSite.cacheAndCall(CachingCallSite.java:318)
        at org.jruby.runtime.callsite.CachingCallSite.call(CachingCallSite.java:155)
        at org.jruby.ir.interpreter.InterpreterEngine.processCall(InterpreterEngine.java:315)
        at org.jruby.ir.interpreter.StartupInterpreterEngine.interpret(StartupInterpreterEngine.java:72)
        at org.jruby.ir.interpreter.Interpreter.INTERPRET_ROOT(Interpreter.java:107)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:94)
        at org.jruby.ir.interpreter.Interpreter.execute(Interpreter.java:34)
        at org.jruby.ir.IRTranslator.execute(IRTranslator.java:42)
        at org.jruby.Ruby.evalScriptlet(Ruby.java:482)
        at org.jruby.Ruby.evalScriptlet(Ruby.java:458)
        at org.asciidoctor.extension.JavaExtensionRegistry.javaImport(JavaExtensionRegistry.java:222)
        at org.asciidoctor.extension.JavaExtensionRegistry.includeProcessor(JavaExtensionRegistry.java:98)
        at org.jqassistant.contrib.plugin.asciidocreport.AsciidocReportPlugin.end(AsciidocReportPlugin.java:104)
        at com.buschmais.jqassistant.core.report.impl.CompositeReportPlugin$2.run(CompositeReportPlugin.java:81)
        at com.buschmais.jqassistant.core.report.impl.CompositeReportPlugin.run(CompositeReportPlugin.java:190)
        at com.buschmais.jqassistant.core.report.impl.CompositeReportPlugin.run(CompositeReportPlugin.java:170)
        at com.buschmais.jqassistant.core.report.impl.CompositeReportPlugin.end(CompositeReportPlugin.java:78)
        at com.buschmais.jqassistant.core.report.impl.InMemoryReportPlugin.end(InMemoryReportPlugin.java:37)
        at com.buschmais.jqassistant.core.analysis.impl.AnalyzerImpl.execute(AnalyzerImpl.java:63)
        at com.buschmais.jqassistant.commandline.task.AnalyzeTask.executeTask(AnalyzeTask.java:68)
        at com.buschmais.jqassistant.commandline.task.AbstractStoreTask.run(AbstractStoreTask.java:55)
        at com.buschmais.jqassistant.commandline.Main.executeTask(Main.java:259)
        at com.buschmais.jqassistant.commandline.Main.executeTasks(Main.java:208)
        at com.buschmais.jqassistant.commandline.Main.interpretCommandLine(Main.java:197)
        at com.buschmais.jqassistant.commandline.Main.run(Main.java:79)
        at com.buschmais.jqassistant.commandline.Main.main(Main.java:50)

**Comment by DirkMahler** [comment]
The issue has been fixed for the core framework, a milestone release is already available (com.buschmais.jqassistant.cli:jqassistant-commandline-neo4jv3:1.7.0-MS3). Due to an interface change the 1.6.0 asciidoc report plugin cannot be used with that milestone, I will release a milestone of this plugin as well.

Note that this plugin will be integrated into the main 1.7.0 distribution.

**Comment by DirkMahler** [comment]
A milestone 1.7.0-MS3 has been released to Maven Central.
